version: '3.8'

services:
  # 应用服务
  smdc-app:
    image: ${REGISTRY}/wechat-smdc-app:${VERSION}
    container_name: wechat-smdc-app
    ports:
      - "${APP_PORT}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://smdc-mysql:3306/${MYSQL_DATABASE}?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - SPRING_REDIS_HOST=smdc-redis
      - SPRING_REDIS_PORT=${REDIS_PORT}
      - SPRING_REDIS_PASSWORD=${REDIS_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - WX_APPID=${WX_APPID}
      - WX_SECRET=${WX_SECRET}
      - WX_MCHID=${WX_MCHID}
      - WX_KEY=${WX_KEY}
      - WX_NOTIFY_URL=${WX_NOTIFY_URL}
      - TZ=${TZ}
      - JAVA_OPTS=${JAVA_OPTS}
    volumes:
      - ${UPLOAD_DIR}:/app/uploads
    depends_on:
      - smdc-mysql
      - smdc-redis
    networks:
      - smdc-network
    restart: always

  # 管理后台前端
  smdc-admin:
    image: ${REGISTRY}/wechat-smdc-admin:${VERSION}
    container_name: wechat-smdc-admin
    ports:
      - "${ADMIN_PORT}:80"
    environment:
      - TZ=${TZ}
    depends_on:
      - smdc-app
    networks:
      - smdc-network
    restart: always

  # MySQL服务
  smdc-mysql:
    image: mysql:8.0.42
    container_name: wechat-smdc-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${TZ}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/
      - ./mysql/conf:/etc/mysql/conf.d/
    command: 
      --character-set-server=utf8mb4 
      --collation-server=utf8mb4_unicode_ci
      --default-time-zone=+8:00
    networks:
      - smdc-network
    restart: always

  # Redis服务
  smdc-redis:
    image: redis:7.2
    container_name: wechat-smdc-redis
    ports:
      - "${REDIS_PORT}:6379"
    environment:
      - TZ=${TZ}
    command: redis-server --appendonly yes ${REDIS_PASSWORD:+--requirepass ${REDIS_PASSWORD}}
    volumes:
      - redis-data:/data
    networks:
      - smdc-network
    restart: always

networks:
  smdc-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data: 