version: '3.8'

services:
  # 应用服务
  app:
    build: .
    container_name: wechat-smdc-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/smdcmanage?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - JAVA_OPTS=-Xms512m -Xmx512m -Djava.security.egd=file:/dev/./urandom
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mysql
      - redis
    networks:
      - smdc-network
    restart: always

  # MySQL服务
  mysql:
    image: mysql:5.7
    container_name: wechat-smdc-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=smdcmanage
      - TZ=Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/
      - ./mysql/conf:/etc/mysql/conf.d/
    command: 
      --character-set-server=utf8mb4 
      --collation-server=utf8mb4_unicode_ci
      --default-time-zone=+8:00
    networks:
      - smdc-network
    restart: always

  # Redis服务
  redis:
    image: redis:6.2
    container_name: wechat-smdc-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - smdc-network
    restart: always

networks:
  smdc-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data: 